-- MySQL Script generated by MySQL Workbench
-- Mon Jul 29 10:54:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `carteira` VARCHAR(10) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `login` VARCHAR(20) NULL,
  `senha` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `tipo_usuario` TINYINT NULL,
  `idfuncao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_funcao1_idx` (`idfuncao` ASC),
  CONSTRAINT `fk_usuario_funcao1`
    FOREIGN KEY (`idfuncao`)
    REFERENCES `mydb`.`funcao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `cnpj` VARCHAR(20) NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `telefone2` VARCHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrega` DATE NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `idcliente` INT NOT NULL,
  `idfuncionario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_usuario1_idx` (`idfuncionario` ASC),
  INDEX `fk_pedido_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `qtde` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `foto` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `cor` VARCHAR(30) NOT NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_categoria1_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_pedido` (
  `idpedido` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `qtde` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `prioridade` VARCHAR(5) NOT NULL,
  `status` TINYINT NOT NULL,
  INDEX `fk_item_pedido_pedido_idx` (`idpedido` ASC),
  INDEX `fk_item_pedido_produto1_idx` (`idproduto` ASC),
  PRIMARY KEY (`idproduto`, `idpedido`),
  CONSTRAINT `fk_item_pedido_pedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idfuncionario` INT NOT NULL,
  `data_entrega` DATE NOT NULL,
  `data_lancamento` DATE NOT NULL,
  `observacao` VARCHAR(100) NOT NULL,
  `andamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producao_usuario1_idx` (`idfuncionario` ASC),
  CONSTRAINT `fk_producao_usuario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_producao` (
  `idproduto` INT NOT NULL,
  `idproducao` INT NOT NULL,
  `idfuncionario` INT NOT NULL,
  `prioridade` VARCHAR(20) CHARACTER SET 'armscii8' NOT NULL,
  `qtde` INT NOT NULL,
  `qtde_perda` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `idproducao`),
  INDEX `fk_item_producao_producao1_idx` (`idproducao` ASC),
  INDEX `fk_item_producao_usuario1_idx` (`idfuncionario` ASC),
  INDEX `fk_item_producao_produto1_idx` (`idproduto` ASC),
  CONSTRAINT `fk_item_producao_producao1`
    FOREIGN KEY (`idproducao`)
    REFERENCES `mydb`.`producao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_producao_usuario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_producao_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `qtde` INT NOT NULL,
  `foto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_produto` (
  `idpeca` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `qtde` INT NOT NULL,
  INDEX `fk_peca_has_produto_produto1_idx` (`idproduto` ASC),
  INDEX `fk_peca_has_produto_peca1_idx` (`idpeca` ASC),
  PRIMARY KEY (`idpeca`, `idproduto`),
  CONSTRAINT `fk_peca_has_produto_peca1`
    FOREIGN KEY (`idpeca`)
    REFERENCES `mydb`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_has_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `mydb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producao_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producao_peca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_lancamento` DATE NOT NULL,
  `data_entrega` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `idfuncionario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producao_peca_funcionario1_idx` (`idfuncionario` ASC),
  CONSTRAINT `fk_producao_peca_funcionario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_producao_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_producao_peca` (
  `idpeca` INT NOT NULL,
  `idproducao_peca` INT NOT NULL,
  `qtde` INT NOT NULL,
  `qtde_perda` INT NOT NULL,
  `prioridade` VARCHAR(5) NOT NULL,
  `idfuncionario` INT NOT NULL,
  PRIMARY KEY (`idpeca`, `idproducao_peca`),
  INDEX `fk_peca_has_producao_peca_producao_peca1_idx` (`idproducao_peca` ASC),
  INDEX `fk_peca_has_producao_peca_peca1_idx` (`idpeca` ASC),
  INDEX `fk_item_producao_peca_funcionario1_idx` (`idfuncionario` ASC),
  CONSTRAINT `fk_peca_has_producao_peca_peca1`
    FOREIGN KEY (`idpeca`)
    REFERENCES `mydb`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_has_producao_peca_producao_peca1`
    FOREIGN KEY (`idproducao_peca`)
    REFERENCES `mydb`.`producao_peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_producao_peca_funcionario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
