-- MySQL Script generated by MySQL Workbench
-- Fri Jun 14 09:57:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `altura` FLOAT NOT NULL,
  `peso` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `contato` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tratamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tratamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `exercicio` VARCHAR(250) NOT NULL,
  `medicamento` VARCHAR(100) NOT NULL,
  `alimentacao` VARCHAR(500) NOT NULL,
  `tipo_tratamento` INT NOT NULL,
  `idespecialista` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tratamento_especialista1_idx` (`idespecialista` ASC),
  CONSTRAINT `fk_tratamento_especialista1`
    FOREIGN KEY (`idespecialista`)
    REFERENCES `mydb`.`especialista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resultado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imc` FLOAT NOT NULL,
  `data` DATE NOT NULL,
  `classificacao` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idtratamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resultado_usuario_idx` (`idusuario` ASC),
  INDEX `fk_resultado_tratamento1_idx` (`idtratamento` ASC),
  CONSTRAINT `fk_resultado_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultado_tratamento1`
    FOREIGN KEY (`idtratamento`)
    REFERENCES `mydb`.`tratamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
